version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - echo "Compiling Java app..."
      - javac HelloWorld.java
      - echo "Build complete"
artifacts:
  files:
    - HelloWorld.java
    - HelloWorld.class
